### ISSUE TITLE
It stopped working today

### ISSUE THREAD

**Issue by noeleo25** [Digitalbrainstem/Javascript-Vue#5]
Files that was working past week yesterday stopped working, it does not recognize template syntax anymore.
![Captura](https://user-images.githubusercontent.com/7296318/72822585-5895b080-3c40-11ea-973a-ec75f38b5e1f.PNG)

**Comment by Betanu701** [comment]
Place the opening tick '`' on the first line with the template. I did not want to make it so that all `` had html just in case. I wanted just the template and the only way to do this is to have it on the same line. The closing does not matter.

**Comment by noeleo25** [comment]
Yes! It works now! Thanks 👍
